# Generated by Django 3.0.8 on 2020-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_type', models.CharField(max_length=2)),
                ('sap_id', models.CharField(max_length=18)),
                ('host_name', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('is_active', models.BooleanField(default=True, help_text='For Soft Delete')),
            ],
        ),
    ]
