# Generated by Django 3.0.8 on 2020-07-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='host_name',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='loopback',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
