# Generated by Django 3.0.8 on 2020-07-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_auto_20200702_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ('-id',)},
        ),
    ]
